# fantasy/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LeagueViewSet, ProfileUpdateView

# Set up the router for the League viewset
router = DefaultRouter()
router.register(r'leagues', LeagueViewSet, basename='league')  # Creates routes like /api/leagues/ and /api/leagues/<id>/

# Include the routes generated by the router and the profile update endpoint
urlpatterns = [
    path('', include(router.urls)),  # League routes
    path('profile/', ProfileUpdateView.as_view(), name='profile-update'),  # Profile update route
]

