# fantasy/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LeagueViewSet

# Register the viewset with the router
router = DefaultRouter()
router.register(r'fantasy', LeagueViewSet, basename='league')  # Creates routes for LeagueViewSet

# Include all routes generated by the router
urlpatterns = [
    path('', include(router.urls)),  # Now includes routes like /api/fantasy/ and /api/fantasy/<id>/
]
