name: Apex Fantasy Football Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI Job
  build:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py migrate
        python manage.py test

  # CodeQL Job
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  # Super Linter Job
  linter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super Linter
      uses: github/super-linter@v4

  # WIP (Work In Progress) Job
  wip:
    name: WIP (Work In Progress) Check
    runs-on: ubuntu-latest

    steps:
    - name: Check if WIP
      uses: andymckay/labeler-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        search-term: 'WIP'
        label-name: 'WIP'

  # Cypress E2E Tests Job
  cypress:
    name: Cypress End-to-End (E2E) Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cypress:run

  # CodeCov (Test Coverage) Job
  codecov:
    name: CodeCov Test Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-upload
        fail_ci_if_error: true

  # Docker Build and Push Job
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t apex-fantasy-football:latest .
        docker tag apex-fantasy-football:latest mydockerhub/apex-fantasy-football:latest
        docker push mydockerhub/apex-fantasy-football:latest
