# .github/workflows/ci.yml
name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django coverage codecov

      - name: Set up the database
        env:
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
        run: |
          python manage.py migrate

      - name: Run Tests with Coverage
        env:
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          flags: unittests
          name: codecov-report
